export default ({gain, frequency, detune = 12, startTime, stopTime}) => ({
  0: ['gain', 'output', {gain}],
  1: ['oscillator', 0, {detune: -3 * detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  2: ['oscillator', 0, {detune: -2 * detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  3: ['oscillator', 0, {detune: -detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  4: ['oscillator', 0, {detune: 0,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  5: ['oscillator', 0, {detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  6: ['oscillator', 0, {detune: 2 * detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
  7: ['oscillator', 0, {detune: 3 * detune,
                        frequency,
                        startTime,
                        stopTime,
                        type: 'sawtooth'}],
})
