const computedStyle = getComputedStyle(document.body)
const prop = name => computedStyle.getPropertyValue(name).trim()

export const blue10 = prop('--blue-10')
export const gray99 = prop('--gray-99')
export const green50 = prop('--green-50')
export const pink50 = prop('--pink-50')
export const red10 = prop('--red-10')
export const red50 = prop('--red-50')
export const turquoise = prop('--turquoise')
