export const UPDATE_ARPEGGIATOR_IS_ON = 'UPDATE_ARPEGGIATOR_IS_ON';
export const UPDATE_SELECTED_EFFECT = 'UPDATE_SELECTED_EFFECT';
export const UPDATE_SELECTED_INSTRUMENT = 'UPDATE_SELECTED_INSTRUMENT';
export const UPDATE_SELECTED_PATTERN = 'UPDATE_SELECTED_PATTERN';
export const UPDATE_SELECTED_SCALE = 'UPDATE_SELECTED_SCALE';
export const UPDATE_ROOT_NOTE = 'UPDATE_ROOT_NOTE';
